/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** caller should guarantee buffer could convert to valid utf8 string */
export function compileSyncBuffer(source: Buffer): string
export function compileSync(source: string): string
