[package]
name = "vue-compiler-dom"
version = "0.1.0"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler = { path = "../compiler", default-features = false, features = [], package = "vue-compiler-core" }
phf = { version = "0.11", features = ["macros"] }
